GET http://localhost:5132
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Imt1dHR5Iiwic3ViIjoia3V0dHkiLCJqdGkiOiI0YjBjYWY2NyIsInJvbGUiOiJhZG1pbiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjU5MzY5IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNTciLCJodHRwOi8vbG9jYWxob3N0OjUxMzIiLCJodHRwczovL2xvY2FsaG9zdDo3MDA4Il0sIm5iZiI6MTY3NTM0MDY4MCwiZXhwIjoxNjgzMDMwMjgwLCJpYXQiOjE2NzUzNDA2ODEsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.1hFCUs8drxJUiCzvRxqm65R6T8gIIdUmo97CfjAY6p4

###
GET http://localhost:5132/kutty
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Imt1dHR5Iiwic3ViIjoia3V0dHkiLCJqdGkiOiIzODNkY2Q5MiIsInJvbGUiOiJjdXN0b21lciIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjU5MzY5IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNTciLCJodHRwOi8vbG9jYWxob3N0OjUxMzIiLCJodHRwczovL2xvY2FsaG9zdDo3MDA4Il0sIm5iZiI6MTY3NTM0NTYxMCwiZXhwIjoxNjgzMDM1MjEwLCJpYXQiOjE2NzUzNDU2MTEsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.7V1lrVM0UXDUube6uPE_OSTCrCji-jvQEvA8doA9dOw

### 
GET http://localhost:5132/subs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Imt1dHR5Iiwic3ViIjoia3V0dHkiLCJqdGkiOiIxNjcwMjQ3MSIsInJvbGUiOiJjdXN0b21lciIsInN1YnNjcmlwdGlvbiI6ImdvbGQiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1OTM2OSIsImh0dHBzOi8vbG9jYWxob3N0OjQ0MzU3IiwiaHR0cDovL2xvY2FsaG9zdDo1MTMyIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzAwOCJdLCJuYmYiOjE2NzUzNTAyMzIsImV4cCI6MTY4MzAzOTgzMiwiaWF0IjoxNjc1MzUwMjMzLCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.mwiC_GeBtyTC2kebZwRXXSAY-VGq32C4BZ5z5wtKgcQ

###
